### ISSUE TITLE
Using Prolog for access control logic

### ISSUE THREAD

**Issue by alexweissman** [Trismegiste/Prolog#1]
Hi,

I'm working on a web-based user management system (https://github.com/alexweissman/UserFrosting), and I'm trying to improve our authorization/access control system.  Basically, the goal is to allow arbitrary rules to be written for authorizing user X to perform some action Y with parameters Z.  The idea is to go beyond a traditional access control list, which is not Turing complete and thus makes it difficult to realize complex rules.

I recall spending a few weeks on Prolog as an undergrad, and it occurred to me that this would be a perfect solution.  This project seems like it might be what UserFrosting needs, but I noticed that it hasn't been updated in a while.

Would you recommend your Prolog interpreter for our project?  Is this project a "mature" technology?

**Comment by CMCDragonkai** [comment]
@alexweissman In a way you're describing ABAC (attribute based access control). In the last 3 years, have you kept with using prolog?

**Comment by alexweissman** [comment]
Nope!  I was ultimately convinced that this would be a bad idea, mainly due to "unintended consequences": https://softwareengineering.stackexchange.com/questions/266205/using-prolog-to-implement-authorization-rules

A shame though; it would be a very elegant way to implement ABAC.  Ultimately I went with a sort of RBAC+, that allows you to [define programmatic conditions](https://learn.userfrosting.com/users/access-control#access-conditions) on permissions.
